### ISSUE TITLE
Breaking outside browser environment

### ISSUE THREAD

**Issue by lcsrinaldi** [soska/keyboardist#8]
Specifically on SSR apps.

This [line](https://github.com/soska/keyboardist/blob/master/src/lib/index.js#L11) isn't working as it's supposed to.
Check this example on [babel playground](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FAYw9gdgzmA2CmA6WYDmAKALgTwA7zADMACAQ2IF4riByAVwgBN5CBLCeRmgSgG5RIMBMjRY8BEuSoViDZmw6M-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=).

**Comment by soska** [comment]
Crap. Undefined should be in quotes there. I’m AFK right now but will fix ASAP.

**Comment by lcsrinaldi** [comment]
@soska if you need help I can open a PR for both issues I've opened. Let me know.

**Comment by lcsrinaldi** [comment]
@soska sorry for the delay. Had some time on the weekend to do this, opened two PRs. 👍
